### ISSUE TITLE
No module named 'social_django'/'social'

### ISSUE THREAD

**Issue by SirRenfri** [omab/python-social-auth#1082]
Hello. I installed social-auth-app-django, but if I try to run migrate, I get following error message:
`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 327, in execute
    django.setup()
  File "C:\Python34\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python34\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Python34\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'social_django'
`

If I use python-social-auth, I get following the same error message:
`
ImportError: No module named 'social'
`

**Comment by berluskuni** [comment]
Hi, I'm using python 3.5 Django==1.10 I installed Python-social-auth executed the command Python manage.py transfer error received!
python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/berluskuni/web_project/exprender/.exprender/lib64/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/berluskuni/web_project/exprender/.exprender/lib64/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/berluskuni/web_project/exprender/.exprender/lib64/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/berluskuni/web_project/exprender/.exprender/lib64/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/berluskuni/web_project/exprender/.exprender/lib64/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/berluskuni/web_project/exprender/.exprender/lib64/python3.5/site-packages/social/apps/django_app/default/models.py", line 1, in <module>
    from social_django.models import AbstractUserSocialAuth, UserSocialAuth, Nonce, Association, Code, DjangoStorage
ImportError: No module named 'social_django'
(.exprender) [*********@localhost exprender]$

**Comment by berluskuni** [comment]
мне помогло установка
pip install python-social-auth[django]`
`or
pip install social-auth-app-django`
`
and in INSTALLED APPS
.....
.....
'social_django',
'social.apps.django_app.default',
Good luck

**Comment by jpic** [comment]
See: 

https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md

**Comment by SirRenfri** [comment]
I solved my problem. It was because of I use virtual environment and I forgot active it

**Comment by rifa84** [comment]
I have the same problem, and virtualenv is active, but the same error "No module named social_djano"

**Comment by amrhassab** [comment]
> I solved my problem. It was because virtual environment. I forgot active it

Also dont forget to enter shell before installing for example run 'pipenv shell'
