### ISSUE TITLE
Python-social-auth throwing error that module not found: No module named 'django.core.urlresolvers'

### ISSUE THREAD

**Issue by parvez301** [omab/python-social-auth#1090]
I'm using python 3.6.0 along with Django 2.0 trying to implement social login in my web application, after installing python-social-auth when I added 'social.apps.django_app.default' to installed apps, the server is printing following traceback.
    `Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x104650b70>
Traceback (most recent call last):
  File "/Users/parvez/.virtualenvs/djangodev/lib/python3.6/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/parvez/.virtualenvs/djangodev/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 115, in inner_run
    autoreload.raise_last_exception()
  File "/Users/parvez/.virtualenvs/djangodev/lib/python3.6/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/parvez/.virtualenvs/djangodev/lib/python3.6/site-packages/django/utils/six.py", line 683, in reraise
    raise value.with_traceback(tb)
  File "/Users/parvez/.virtualenvs/djangodev/lib/python3.6/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/parvez/.virtualenvs/djangodev/lib/python3.6/site-packages/django/__init__.py", line 25, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/parvez/.virtualenvs/djangodev/lib/python3.6/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/Users/parvez/.virtualenvs/djangodev/lib/python3.6/site-packages/social/apps/django_app/default/config.py", line 11, in ready
    from social.apps.django_app.utils import load_strategy
  File "/Users/parvez/.virtualenvs/djangodev/lib/python3.6/site-packages/social/apps/django_app/utils.py", line 6, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
    `

**Comment by omab** [comment]
`python-social-auth` doesn't support Django 2.0 yet. The proper place to open a ticket related to Django would be in the https://github.com/python-social-auth/social-app-django project.
