### ISSUE TITLE
Facebook login fails with  KeyError: 'access_token'

### ISSUE THREAD

**Issue by ajoyoommen** [omab/python-social-auth#1094]
This is the stack trace:

    Internal Server Error: /complete/facebook/
    Traceback (most recent call last):
      File "/home/ec2-user/project/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/home/ec2-user/project/venv/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
        return view_func(*args, **kwargs)
      File "/home/ec2-user/project/venv/local/lib/python2.7/site-packages/social/apps/django_app/utils.py", line 52, in wrapper
        return func(request, backend, *args, **kwargs)
      File "/home/ec2-user/project/venv/local/lib/python2.7/site-packages/social/apps/django_app/views.py", line 20, in complete
        redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)
      File "/home/ec2-user/project/venv/local/lib/python2.7/site-packages/social/actions.py", line 43, in do_complete
        user = backend.complete(user=user, *args, **kwargs)
      File "/home/ec2-user/project/venv/local/lib/python2.7/site-packages/social/backends/base.py", line 40, in complete
        return self.auth_complete(*args, **kwargs)
      File "/home/ec2-user/project/venv/local/lib/python2.7/site-packages/social/backends/facebook.py", line 71, in auth_complete
        access_token = response['access_token']
    KeyError: 'access_token'

* Python social auth: 0.2.1

* Facebook app: v2.2

* Since: March 28, 2017 (as v2.2 was deprecated on March 27). Updated the Facebook App to latest, but the error persists.

**Comment by nony05** [comment]
+1

**Comment by sametersan** [comment]
+1

**Comment by scottlinux** [comment]
Does the latest python-social-auth work? (0.3.6)

**Comment by scottlinux** [comment]
Try python-social-auth==0.2.21

**Comment by ajoyoommen** [comment]
I was unable to upgrade to latest. However, upgrading to 0.2.19 worked and also solved this issue.
