### ISSUE TITLE
AuthStateMissing: Session value state missing

### ISSUE THREAD

**Issue by dtrst** [omab/python-social-auth#279]
Hi. I have some problem with fb auth. Maybe this is bug? 
1. I registered fb application on facebook.com
2. Installed test application with virtualenv 

```
Django==1.6.5
argparse==1.2.1
oauthlib==0.6.1
python-openid==2.2.5
python-social-auth==0.1.23
requests==2.2.1
requests-oauthlib==0.4.0
six==1.6.1
wsgiref==0.1.2
```
1. I do test auth request and app crash =(

```
Django version 1.5, using settings 'example.settings'
Development server is running at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /complete/facebook/
Traceback (most recent call last):
  File "/home/suwer/.venv/eng/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/suwer/.venv/eng/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "../../social/apps/django_app/utils.py", line 45, in wrapper
    return func(request, backend, *args, **kwargs)
  File "../../social/apps/django_app/views.py", line 21, in complete
    redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)
  File "../../social/actions.py", line 44, in do_complete
    *args, **kwargs)
  File "../../social/strategies/base.py", line 71, in complete
    return self.backend.auth_complete(*args, **kwargs)
  File "../../social/backends/facebook.py", line 62, in auth_complete
    state = self.validate_state()
  File "../../social/backends/oauth.py", line 307, in validate_state
    raise AuthStateMissing(self, 'state')
AuthStateMissing: Session value state missing.
[16/May/2014 12:54:10] "GET /complete/facebook/?redirect_state=8vGFbbjtD8Q3VFvB8E1AjpJIIIrMtxW5&code=AQB1-SM-My7n0uiSCtos10iI_qEAi8_QjTPdplWfnxYuSlmoKZrYa2y0SZy8OTBab5I5A1sFIqSZNyDVwHN570NiEyvF4YohZMJxSeGXWyYa5QSil-qBvsfA2BT1pjPa_6ASCQFZBwXJn4EyOXTdrQzPej2m49FRSPDPetneA4SpxOsEyqqCRYiLdUxKIfmYjsLhqxgiTpJhBIU55ktMSOIh7HzzFEtoaE_q25knwo042z3X7Zm7q7LQeVTzbgi8TPg2rsBeIqesTWSfJdHMCuDlGuaS6TEeCMYNbVhbFoXYQk1-kJWkuJkZzFF6e8udQos&state=8vGFbbjtD8Q3VFvB8E1AjpJIIIrMtxW5 HTTP/1.1" 500 144223

```

```
../../social/backends/oauth.py in validate_state
            raise AuthStateMissing(self, 'state') ...
▼ Local vars
Variable    Value
request_state   u'eM3VOv6WnpLcneVEuEDGzIublSQiKMez'
state     None
self    <social.backends.facebook.FacebookOAuth2 object at 0x7fe69c3c6a10>
```
1. Test some last version django (1.5, 1.6)  + chrome, firefox

Thank you.

**Comment by ericson-cepeda** [comment]
#534
