### ISSUE TITLE
AuthState missing for LinkedIn OAUTH2?

### ISSUE THREAD

**Issue by bertenator** [omab/python-social-auth#365]
social.exceptions.AuthStateMissing
AuthStateMissing: Session value state missing.

Traceback (most recent call last)
File "/opt/a/virtualenvs/pyappd/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 255, in **call**
response = self.get_response(request)
File "/opt/a/virtualenvs/pyappd/lib/python2.7/site-packages/django/core/handlers/base.py", line 178, in get_response
response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
File "/opt/a/virtualenvs/pyappd/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
response = callback(request, _callback_args, *_callback_kwargs)
File "/opt/a/virtualenvs/pyappd/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
return view_func(_args, *_kwargs)
File "/opt/a/virtualenvs/pyappd/lib/python2.7/site-packages/social/apps/django_app/utils.py", line 45, in wrapper
return func(request, backend, _args, *_kwargs)
File "/opt/a/virtualenvs/pyappd/lib/python2.7/site-packages/social/apps/django_app/views.py", line 21, in complete
redirect_name=REDIRECT_FIELD_NAME, _args, *_kwargs)
File "/opt/a/virtualenvs/pyappd/lib/python2.7/site-packages/social/actions.py", line 44, in do_complete
_args, *_kwargs)
File "/opt/a/virtualenvs/pyappd/lib/python2.7/site-packages/social/strategies/base.py", line 71, in complete
return self.backend.auth_complete(_args, *_kwargs)
File "/opt/a/virtualenvs/pyappd/lib/python2.7/site-packages/social/backends/oauth.py", line 345, in auth_complete
data=self.auth_complete_params(self.validate_state()),
File "/opt/a/virtualenvs/pyappd/lib/python2.7/site-packages/social/backends/oauth.py", line 307, in validate_state
raise AuthStateMissing(self, 'state')

AuthStateMissing: Session value state missing.

I'm running into the above exception when trying to use linkedin OAUTH2. It seems like the following line is returning None:

> > > self.strategy.session_get(self.name + '_state')
> > > 
> > > self.strategy
> > > <social.strategies.django_strategy.DjangoStrategy object at 0x5459390>

**Comment by abhimskywalker** [comment]
+1 
We have been getting the same error for LinkedIn sporadically as well. It's not predictable. It seems somewhere the session information is lost/modified, but we haven't been able to replicate the errors as well.

Just wanted to ask if it makes sense to build a small snippet to maybe restart the whole request response cycle in this case once more for this failure? I haven't as yet looked into the code fully in detail if this is possible or not, but hypothesis is that is the failure is a random event (specifically if the exception is `AuthStateMissing`) then when we encounter this let's just try to restart the whole process of auth request cycle. 
This essentially means that we are just trying to maximise our chances of getting a proper response (hopefully this random event will not repeat twice in a row). Let me know what do you guys think? 
Might try to test this out sometime soon, but have no clear way to reproduce this error as yet to test if this will work or not.

**Comment by pgcd** [comment]
i'm not sure if this is actually the same issue but I'm getting the error frequently (1/hour) and in my case it's apparently due to the user cancelling the request: this is what the query_dict looks like:

    {u'state': [u'fsA5LYcwGuZaomUEsRJEi4g9iPavXtie'], u'error_description': [u'the user denied your request'], u'error': [u'access_denied']}

**Comment by craig-hacklaunch** [comment]
+1 on this I have seen the same behaviour as pgcd. Is there any workaround suggested?

**Comment by liuminghao1** [comment]
+1  I am also

**Comment by inakrin** [comment]
Same here.

**Comment by omab** [comment]
The state was wrongly checking on error responses, masking the real error as an state missing one. Fixed by https://github.com/python-social-auth/social-core/commit/4d2903c1a26cc433731dcc103fd211a7a4716b96
