### ISSUE TITLE
TypeError: object of type 'map' has no len()

### ISSUE THREAD

**Issue by JJZolper** [omab/python-social-auth#588]
So I updated my PSA since I was told we had made adjustments in relation to just some warnings coming around the bend with django 1.9 and then this happened so I wanted to drop it here in case it was of value. It appears something else has gone wrong:

(athletesunited)JJs-MacBook-Pro:athletesunited JJZ$ python manage.py runserver localhost:8000
/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  return f(*args, **kwds)

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/social/apps/django_app/default/models.py", line 9, in <module>
    from social.storage.django_orm import DjangoUserMixin, \
  File "/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/social/storage/django_orm.py", line 5, in <module>
    from social.storage.base import UserMixin, AssociationMixin, NonceMixin, \
  File "/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/social/storage/base.py", line 12, in <module>
    from openid.association import Association as OpenIdAssociation
  File "/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/openid/__init__.py", line 52, in <module>
    if len(version_info) != 3:
TypeError: object of type 'map' has no len()

**Comment by kyleconroy** [comment]
I just ran into this problem as well

```
$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/kyle/projects/speakers/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/social/apps/django_app/default/models.py", line 9, in <module>
    from social.storage.django_orm import DjangoUserMixin, \
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/social/storage/django_orm.py", line 5, in <module>
    from social.storage.base import UserMixin, AssociationMixin, NonceMixin, \
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/social/storage/base.py", line 12, in <module>
    from openid.association import Association as OpenIdAssociation
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/openid/__init__.py", line 52, in <module>
    if len(version_info) != 3:
TypeError: object of type 'map' has no len()
```

**Comment by tutuca** [comment]
[Release was last night](https://github.com/omab/python-social-auth/commit/c73ad1fbe45121bf00ee56c2bef27b3d0475e542)

**Comment by JJZolper** [comment]
Yeah that's what I am saying. I had pulled the newest release which is yes 0.2.4 and I tried to run the server and it bombed out, the server will not run. And yes it looks like something with open ID so maybe we weren't expecting this as much like tutuca said.

**Comment by yprez** [comment]
Ran into this too...
Looks like, for some reason, when installing from PyPI on Python3 it installs python-openid instead of python3-openid...
When installing from github, or from a local version, it does get the correct version (python3-openid).

**Comment by JJZolper** [comment]
Oh yprez did that do it? Did installing python3-openid do it? I did some research and it did seem like a python3 thing. Basically you had to handle the mapping slightly differently.

**Comment by yprez** [comment]
I checked and after uninstalling python-openid and installing python3-openid manually, it worked. Before that I had problems with it, maybe because of clashes between the 2 openid versions.

The weird things is that when you do `pip install git+https://github.com/omab/python-social-auth.git`, it installs python3-openid properly...

**Comment by JJZolper** [comment]
Yeah you are correct, after uninstalling python-openid and installing python3-openid everything worked out as expected and the server funs fine. I just installed python3-openid directly so pip install python3-openid instead of using PSA because when I first tried that it still installed python-openid instead.

**Comment by h8** [comment]
Same here - after installing latest version with Pip it also installs python-openid instead of installing python3-openid. Python version 3.4.0.

**Comment by omab** [comment]
I've released ``v0.2.5`` which solves this issue, the problem was caused by the recently introduced wheel support, but the packages built was broken (Python 2 dependencies defined in the a single universal wheel), I've fixed it b building version-dependent wheels now.

**Comment by tutuca** [comment]
Thanks!

**Comment by ngavrish** [comment]
Still have this issue with latest from pip and Python 3.4

**Comment by ngavrish** [comment]
Obviously even I fix this by wrapping map in the list, I run into bunch of another issues

**Comment by voylinux** [comment]
Still same problem here
Python 3.4

**Comment by TristanH** [comment]
+1 to issue still existing with Python 3.4

**Comment by masroore** [comment]
Python 3.5.1. issue still existing.

**Comment by guinslym** [comment]
Works great with 3.4. I just had to upgrade the package
`pip install -u python-social-auth`

**Comment by neelshah16** [comment]
I still have the same issue, python 3.6

**Comment by akhilrs** [comment]
Upgrading `python3-openid` solved the issue on python 3.6
`pip3 install python3-openid --upgrade`

**Comment by Rokrishna9** [comment]
Fix this:

 TypeError: object of type 'map' has no len()

**Comment by Rokrishna9** [comment]
If you don't know how to fix it, tell us so we can help you fix it. But fix it.

**Comment by omab** [comment]
@Rokrishna9

1. It's better to propose a fix than demand one
2. This library is deprecated since December 2016

**Comment by vinpalace** [comment]
I've fixed it by uninstalling all the openid packages present and the module I was using. In this case it was  `social-auth-app-django`
```
pip uninstall python-openid
pip uninstall python3-openid
```
Then reinstalled the module which sorted out the correct dependency order.

**Comment by palewire** [comment]
Issue is still with us!

**Comment by shukhrat211** [comment]
I have fixed it by uninstalling pip uninstall python-openid, and  pip uninstall python3-openid then install both  pip install python-openid and pip install python3-openid, but social-auth still not work
