### ISSUE TITLE
Authentication failed: Can't connect to HTTPS URL because the SSL module is not available.

### ISSUE THREAD

**Issue by juliocebrito** [omab/python-social-auth#598]
Authentication failed: Can't connect to HTTPS URL because the SSL module is not available.

**Comment by omab** [comment]
What? Do you have any traceback? Any info?

**Comment by juliocebrito** [comment]
Traceback (most recent call last):
  File "C:\Users\Mr.Julio\Desktop\atcoin\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Mr.Julio\Desktop\atcoin\django\views\decorators\cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Mr.Julio\Desktop\atcoin\social\apps\django_app\utils.py", line 52, in wrapper
    return func(request, backend, *args, **kwargs)
  File "C:\Users\Mr.Julio\Desktop\atcoin\social\apps\django_app\views.py", line 19, in auth
    return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
  File "C:\Users\Mr.Julio\Desktop\atcoin\social\actions.py", line 25, in do_auth
    return backend.start()
  File "C:\Users\Mr.Julio\Desktop\atcoin\social\backends\base.py", line 35, in start
    return self.strategy.redirect(self.auth_url())
  File "C:\Users\Mr.Julio\Desktop\atcoin\social\backends\oauth.py", line 165, in auth_url
    token = self.set_unauthorized_token()
  File "C:\Users\Mr.Julio\Desktop\atcoin\social\backends\oauth.py", line 221, in set_unauthorized_token
    token = self.unauthorized_token()
  File "C:\Users\Mr.Julio\Desktop\atcoin\social\backends\oauth.py", line 241, in unauthorized_token
    method=self.REQUEST_TOKEN_METHOD
  File "C:\Users\Mr.Julio\Desktop\atcoin\social\backends\base.py", line 224, in request
    raise AuthFailed(self, str(err))
AuthFailed: Authentication failed: Can't connect to HTTPS URL because the SSL module is not available.
INFO     2015-04-20 14:35:15,645 module.py:788] default: "GET /login/twitter HTTP/1.1" 500 88984

**Comment by juliocebrito** [comment]
Hola, Gracias Matias por tu tiempo, yo soy julio de colombia, mira con django funciona perfectamente, pero yo estoy usando djangae que es una aplicacion para usar django en app engine de Google https://github.com/potatolondon/djangae

**Comment by omab** [comment]
It looks like your python setup is broken and lacks some modules, check that you have the SSL dependencies when installing it.

**Comment by juliocebrito** [comment]
def request(self, url, method='GET', *args, **kwargs):
        kwargs.setdefault('headers', {})
        if self.setting('VERIFY_SSL') is not None:
            kwargs.setdefault('verify', self.setting('VERIFY_SSL'))
        kwargs.setdefault('timeout', self.setting('REQUESTS_TIMEOUT') or
                                     self.setting('URLOPEN_TIMEOUT'))

        if self.SEND_USER_AGENT and 'User-Agent' not in kwargs['headers']:
            kwargs['headers']['User-Agent'] = user_agent()

        try:
            response = request(method, url, *args, **kwargs)
        except ConnectionError as err:
            raise AuthFailed(self, str(err))
        response.raise_for_status()
        return response

**Comment by omab** [comment]
The problem is not with ``python-social-auth`` or ``requests``, it's withing your Python installation which lacks SSL support (needed to connect to any SSL-based service), you need to recompile Python with SSL support, or reinstall a version with it.

**Comment by juliocebrito** [comment]
please tell me python-social-auth work on app engine?

**Comment by omab** [comment]
I've never tried it, but AFAIK it works.
