### ISSUE TITLE
AuthStateMissing: Session value state missing on web.py example integration

### ISSUE THREAD

**Issue by crashtext** [omab/python-social-auth#611]
Hello, 

Here is my dependencies : 
```
web.py==0.37
sqlalchemy==1.0.1
python-social-auth==0.2.7
jinja2==2.7.3
```

I just implement the example provided in the source for a web.py integration and test it with a Facebook oauth2 provider that's work before with a builtin connector.

Here is the main part code of main.py :
```
web.config[setting_name('USER_MODEL')] = 'model.People'

import model 

web.config[setting_name('LOGIN_REDIRECT_URL')] = '/done/'
web.config[setting_name('NEW_ASSOCIATION_REDIRECT_URL')] = '/done/'

web.config[setting_name('FACEBOOK_KEY')] = 'XXXXX'
web.config[setting_name('FACEBOOK_SECRET')] = 'XXXXX'
web.config[setting_name('FACEBOOK_SCOPE')] = ['public_profile','email','user_friends','user_about_me','user_hometown','user_location']
web.config[setting_name('AUTHENTICATION_BACKENDS')] = (
    'social.backends.facebook.Facebook2OAuth2',
)
urls = (
    '^/$', 'main',
    '^/done/$', 'done',
    '', social_app.app_social
)

engine = create_engine(SQL_URI, echo=DEBUG_MODE, encoding='utf-8')

render = render_jinja('social_auth_templates/')


class main(object):
    def GET(self):
        return render.home()


class done(social_app.BaseViewClass):
    def GET(self):
        user = self.get_current_user()
        return render.done(user=user, backends=backends(user))


def load_sqla(handler):
    web.ctx.orm = scoped_session(sessionmaker(bind=engine))
    try:
        return handler()
    except web.HTTPError:
        web.ctx.orm.commit()
        raise
    except:
        web.ctx.orm.rollback()
        raise
    finally:
        web.ctx.orm.commit()
        # web.ctx.orm.expunge_all()


Session = sessionmaker(bind=engine)
Session.configure(bind=engine)

app = web.application(urls, locals())
app.add_processor(load_sqla)

web.web_session = web.session.Session(app, web.session.DiskStore('/tmp/sessions'))
web.db_session = Session()

```
When I click on the Facebook link, the redirections works to my website, but I've got the Exception bellow : 

```
127.0.0.1:56288 - - [09/May/2015 10:22:04] "HTTP/1.1 GET /login/facebook/" - 303 See Other
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/Library/Python/2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/Library/Python/2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/Library/Python/2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "/Library/Python/2.7/site-packages/python_social_auth-0.2.7-py2.7.egg/social/apps/webpy_app/app.py", line 52, in GET
    return self._complete(backend, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/python_social_auth-0.2.7-py2.7.egg/social/apps/webpy_app/utils.py", line 43, in wrapper
    return func(self, backend, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/python_social_auth-0.2.7-py2.7.egg/social/apps/webpy_app/app.py", line 62, in _complete
    user=self.get_current_user(), *args, **kwargs
  File "/Library/Python/2.7/site-packages/python_social_auth-0.2.7-py2.7.egg/social/actions.py", line 43, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/python_social_auth-0.2.7-py2.7.egg/social/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/python_social_auth-0.2.7-py2.7.egg/social/utils.py", line 202, in wrapper
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/python_social_auth-0.2.7-py2.7.egg/social/backends/facebook.py", line 71, in auth_complete
    state = self.validate_state()
  File "/Library/Python/2.7/site-packages/python_social_auth-0.2.7-py2.7.egg/social/backends/oauth.py", line 88, in validate_state
    raise AuthStateMissing(self, 'state')
AuthStateMissing: Session value state missing.
```

I found in other issues that this error is due to a lack of session persistence of the state, actually when I unpick the data store in file session this property is not set.

What did I miss ?

**Comment by crashtext** [comment]
when testing with current python-social-auth==0.2.10, it done the same result

**Comment by crashtext** [comment]
I try to test a workaround like bellow : 
```
def load_sqla(handler):
    web.ctx.orm = scoped_session(sessionmaker(bind=engine))
    get_data = web.input()

    if get_data.has_key('redirect_state'):
        web.web_session['facebook_state'] = get_data['redirect_state']


    try:
        return handler()
    except web.HTTPError:
        web.ctx.orm.commit()
        raise
    except:
        web.ctx.orm.rollback()
        raise
    finally:
        web.ctx.orm.commit()
```

And now it pass : 
```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): graph.facebook.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /v2.3/oauth/access_token?client_secret=[snipped]&code=[snipped]&client_id=[snipped]&redirect_uri=http%3A%2F%2Ftheater.greenmango.net%3A8080%2Fcomplete%2Ffacebook%2F%3Fredirect_state%3DJyGaQfieqg5FCzDLquwAUwavDI2RnrX4 HTTP/1.1" 200 285
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): graph.facebook.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /v2.3/me?access_token=[snipped]&appsecret_proof=[snipped] HTTP/1.1" 200 580
```

I test the https requests and Facebook answer correct data.

But unfortunately, there is no user store in database.

**Comment by crashtext** [comment]
Ok, I solve the problem without any hack.
I just forget to code and import the migrate.py ...
