### ISSUE TITLE
Duplicate entry error when updating an existing user with a social user

### ISSUE THREAD

**Issue by marinopv** [omab/python-social-auth#63]
I have a custom model where I use email as the unique identification. When I have created a user with the email address example@example.com and then register a new user with the facebook social backend I get a dupicate entry error.

As I recall using the older django-social-auth 7.28 the existing user got updated. Now this doesn't happen, and it doesn't matter if I use username or email as the identification. I get the error.

If you need some more info please ask me.

(1062, "Duplicate entry 'example@example.com' for key 'email'")

Here is the traceback

```
[22/Oct/2013 11:41:39] "GET /login/facebook/ HTTP/1.1" 302 0
Internal Server Error: /complete/facebook/
Traceback (most recent call last):
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/social/apps/django_app/utils.py", line 32, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/social/apps/django_app/views.py", line 25, in complete
    redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/social/actions.py", line 54, in do_complete
    *args, **kwargs)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/social/strategies/base.py", line 69, in complete
    return self.backend.auth_complete(*args, **kwargs)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/social/backends/facebook.py", line 74, in auth_complete
    return self.do_auth(access_token, response, *args, **kwargs)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/social/backends/facebook.py", line 106, in do_auth
    return self.strategy.authenticate(*args, **kwargs)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/social/strategies/django_strategy.py", line 69, in authenticate
    return authenticate(*args, **kwargs)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 60, in authenticate
    user = backend.authenticate(**credentials)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/social/backends/base.py", line 78, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/social/backends/base.py", line 81, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/social/backends/base.py", line 107, in run_pipeline
    result = func(*args, **out) or {}
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/social/pipeline/user.py", line 91, in user_details
    strategy.storage.user.changed(user)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/social/storage/django_orm.py", line 13, in changed
    user.save()
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/django/db/models/base.py", line 626, in save_base
    rows = manager.using(using).filter(pk=pk_val)._update(values)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/django/db/models/query.py", line 605, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1014, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 122, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/Users/marinopallvaldimarsson/.virtualenvs/gracipe/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1062, "Duplicate entry 'marinopv@gmail.com' for key 'email'")
```

This is my user model

``` python
class MyUserManager(BaseUserManager):
    def create_user(self, email, username=None, password=None, date_of_birth=None, **extra_fields):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        username=email
        if not email:
            raise ValueError('Users must have an email address')

        # if not password:
        #     raise ValueError('Users must have an password')

        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user



    def create_superuser(self, email, password, date_of_birth=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(email,
            password=password,
            date_of_birth=date_of_birth
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
        db_index=True,
    )
    first_name = models.CharField(_('first name'), max_length=30, blank=True)

    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    date_of_birth = models.DateField(default=None,blank=True,null=True)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    username = models.CharField(_('username'), max_length=30,
        help_text=_('Required. 30 characters or fewer. Letters, numbers and '
                    '@/./+/-/_ characters'),
        validators=[
            validators.RegexValidator(re.compile('^[\w.@+-]+$'), _('Enter a valid username.'), 'invalid')
        ])
    objects = MyUserManager()

    USERNAME_FIELD = 'email'

    def is_authenticated(self):
        """
        Always return True. This is a way to tell if the user has been
        authenticated in templates.
        """
        return True
    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    # On Python 3: def __str__(self):
    def __unicode__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
```

**Comment by External-dependencies-ol** [comment]
Got the solution I needed https://maven-failsafe-pluginenr.github.io/rfFO64nnqZLagp8A0Ot6VG_UbcY3X1MIKw/
