### ISSUE TITLE
Object of type map has no length

### ISSUE THREAD

**Issue by ngavrish** [omab/python-social-auth#633]
$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/kyle/projects/speakers/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/social/apps/django_app/default/models.py", line 9, in <module>
    from social.storage.django_orm import DjangoUserMixin, \
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/social/storage/django_orm.py", line 5, in <module>
    from social.storage.base import UserMixin, AssociationMixin, NonceMixin, \
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/social/storage/base.py", line 12, in <module>
    from openid.association import Association as OpenIdAssociation
  File "/Users/kyle/projects/speakers/env/lib/python3.4/site-packages/openid/__init__.py", line 52, in <module>
    if len(version_info) != 3:
TypeError: object of type 'map' has no len()

Python 3.4
PSA 0.2.10

**Comment by mackeee-orange** [comment]
I have a same error.

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f35fcbbbd90>
Traceback (most recent call last):
File "/home/christian-ojt/.virtualenvs/probe/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
  fn(*args, **kwargs)
File "/home/christian-ojt/.virtualenvs/probe/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
  autoreload.raise_last_exception()
File "/home/christian-ojt/.virtualenvs/probe/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
  raise _exception[1]
File "/home/christian-ojt/.virtualenvs/probe/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
  autoreload.check_errors(django.setup)()
File "/home/christian-ojt/.virtualenvs/probe/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
  fn(*args, **kwargs)
File "/home/christian-ojt/.virtualenvs/probe/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
  apps.populate(settings.INSTALLED_APPS)
File "/home/christian-ojt/.virtualenvs/probe/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
  app_config.import_models()
File "/home/christian-ojt/.virtualenvs/probe/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
  self.models_module = import_module(models_module_name)
File "/home/christian-ojt/.virtualenvs/probe/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/home/christian-ojt/.virtualenvs/probe/lib/python3.6/site-packages/social_django/models.py", line 10, in <module>
  from .storage import DjangoUserMixin, DjangoAssociationMixin, \
File "/home/christian-ojt/.virtualenvs/probe/lib/python3.6/site-packages/social_django/storage.py", line 8, in <module>
  from social_core.storage import UserMixin, AssociationMixin, NonceMixin, \
File "/home/christian-ojt/.virtualenvs/probe/lib/python3.6/site-packages/social_core/storage.py", line 12, in <module>
  from openid.association import Association as OpenIdAssociation
File "/home/christian-ojt/.virtualenvs/probe/lib/python3.6/site-packages/openid/__init__.py", line 52, in <module>
  if len(version_info) != 3:
TypeError: object of type 'map' has no len()
```
