### ISSUE TITLE
flask_me_example seems to be using SQLAlchemy instead of Mongo for user storage?

### ISSUE THREAD

**Issue by samchristie** [omab/python-social-auth#680]
I set up a flask_me_exmaple and used both OpenID and OAuth2. In both cases the attempt to log in results in the following error (OpenID version):
127.0.0.1 - - [13/Jul/2015 22:22:45] "GET /login/google/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/social/apps/flask_app/utils.py", line 46, in wrapper
    return func(backend, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social/apps/flask_app/routes.py", line 14, in auth
    return do_auth(g.backend)
  File "/usr/local/lib/python2.7/dist-packages/social/actions.py", line 28, in do_auth
    return backend.start()
  File "/usr/local/lib/python2.7/dist-packages/social/backends/base.py", line 35, in start
    if self.uses_redirect():
  File "/usr/local/lib/python2.7/dist-packages/social/backends/open_id.py", line 239, in uses_redirect
    return self.openid_request().shouldSendRedirect()
  File "/usr/local/lib/python2.7/dist-packages/social/backends/open_id.py", line 245, in openid_request
    params))
  File "/usr/local/lib/python2.7/dist-packages/openid/consumer/consumer.py", line 353, in begin
    return self.beginWithoutDiscovery(service, anonymous)
  File "/usr/local/lib/python2.7/dist-packages/openid/consumer/consumer.py", line 376, in beginWithoutDiscovery
    auth_req = self.consumer.begin(service)
  File "/usr/local/lib/python2.7/dist-packages/openid/consumer/consumer.py", line 598, in begin
    assoc = self._getAssociation(service_endpoint)
  File "/usr/local/lib/python2.7/dist-packages/openid/consumer/consumer.py", line 1158, in _getAssociation
    assoc = self.store.getAssociation(endpoint.server_url)
  File "/usr/local/lib/python2.7/dist-packages/social/store.py", line 43, in getAssociation
    for assoc_id, association in self.assoc.oids(server_url, handle):
  File "/usr/local/lib/python2.7/dist-packages/social/storage/base.py", line 199, in oids
    for assoc in cls.get(*_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social/storage/sqlalchemy_orm.py", line 201, in get
    return cls._query().filter_by(_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social/storage/sqlalchemy_orm.py", line 36, in _query
    return cls._session().query(cls)
  File "/usr/local/lib/python2.7/dist-packages/social/apps/flask_app/default/models.py", line 27, in _session
    return cls.app_session
AttributeError: type object 'Association' has no attribute 'app_session'

I cannot find where the app_session was supposed to be set, but I am confused by the use of SQLAlchemy code. Does the example fail to configure the storage backend correctly?

Ideas?

**Comment by omab** [comment]
The new examples at [social-examples](https://github.com/python-social-auth/social-examples) properly corrected this issue.
