### ISSUE TITLE
ImportError: cannot import name request

### ISSUE THREAD

**Issue by y2kfresh** [omab/python-social-auth#691]
Hi, i have a error : 
# python facebook.py

<addr>
Traceback (most recent call last):
  File "facebook.py", line 11, in <module>
    from social.utils import parse_qs, constant_time_compare, handle_http_errors
  File "/usr/local/lib/python2.7/dist-packages/python_social_auth-0.2.12-py2.7.egg/social/utils.py", line 9, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/**init**.py", line 58, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/local/lib/python2.7/dist-packages/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/**init**.py", line 16, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 39, in <module>
    from .request import RequestMethods
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/request.py", line 12, in <module>
    from .filepost import encode_multipart_formdata
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/filepost.py", line 15, in <module>
    from .fields import RequestField
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/fields.py", line 7, in <module>
    import email.utils
  File "/root/python-social-auth/social/backends/email.py", line 5, in <module>
    from social.backends.legacy import LegacyAuth
  File "/usr/local/lib/python2.7/dist-packages/python_social_auth-0.2.12-py2.7.egg/social/backends/legacy.py", line 1, in <module>
    from social.backends.base import BaseAuth
  File "/usr/local/lib/python2.7/dist-packages/python_social_auth-0.2.12-py2.7.egg/social/backends/base.py", line 1, in <module>
    from requests import request, ConnectionError
ImportError: cannot import name request
</addr>

<addr>
Requirement already satisfied (use --upgrade to upgrade): python-openid in /usr/local/lib/python3.2/dist-packages
Requirement already satisfied (use --upgrade to upgrade): requests-oauthlib in /usr/local/lib/python3.2/dist-packages
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy in /usr/local/lib/python3.2/dist-packages
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python3.2/dist-packages
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python3.2/dist-packages
Requirement already satisfied (use --upgrade to upgrade): oauthlib>=0.6.2 in /usr/local/lib/python3.2/dist-packages (from requests-oauthlib)</addr>

**Comment by maxsocl** [comment]
@y2kfresh may be you can try to install `requests` to `python2` an not to `python3`? Or to run a project w/ python3?

**Comment by iepathos** [comment]
Requirement already satisfied is checking your Python 3.2 libs whereas it looks like you're running Django from python 2.7, you can see the difference in the paths.  Like @maxsocl said, just install requests into your python 2.7 libs or run the project from your python3.2 environment and it should work ok for you.
