### ISSUE TITLE
FORM_HTML and Legacy Auth

### ISSUE THREAD

**Issue by bwarren2** [omab/python-social-auth#705]
I am getting an error stacktrace related to the FORM_HTML settings var not being set.  I can't find anything using search on the docs for 1) what this var is or should be, 2) "legacy", as a means of getting insight about this backend.  What is this variable, and what is a sane default for it?

For context, I am using steam auth and email auth.

    Internal Server Error: /login/email
    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
        response = view_func(request, *args, **kwargs)
      File "/app/.heroku/python/lib/python2.7/site-packages/social/apps/django_app/utils.py", line 54, in wrapper
        return func(request, backend, *args, **kwargs)
      File "/app/.heroku/python/lib/python2.7/site-packages/social/apps/django_app/views.py", line 19, in auth
        return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
      File "/app/.heroku/python/lib/python2.7/site-packages/social/actions.py", line 28, in do_auth
        return backend.start()
      File "/app/.heroku/python/lib/python2.7/site-packages/social/backends/base.py", line 37, in start
        return self.strategy.html(self.auth_html())
      File "/app/.heroku/python/lib/python2.7/site-packages/social/backends/legacy.py", line 14, in auth_html
        return self.strategy.render_html(tpl=self.setting('FORM_HTML'))
      File "/app/.heroku/python/lib/python2.7/site-packages/social/strategies/django_strategy.py", line 69, in render_html
        template = loader.get_template_from_string(html)
    AttributeError: 'module' object has no attribute 'get_template_from_string'

**Comment by bwarren2** [comment]
Looks like this is a dupe of #668 .

**Comment by bwarren2** [comment]
I was on 0.2.9.  Upgrading to 0.2.12 resolved this, though there is a different error to address in my implementation.
