### ISSUE TITLE
IOError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by singjie** [omab/python-social-auth#716]
I'm getting this error once in awhile and usually restarting server will work.

Any idea what's wrong?

```
[20/Aug/2015 17:05:25] ERROR [django.request:256] Internal Server Error: /complete/google-oauth2/
Traceback (most recent call last):
  File "/home/u/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/u/venv/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/u/venv/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/u/venv/local/lib/python2.7/site-packages/social/apps/django_app/utils.py", line 51, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/home/u/venv/local/lib/python2.7/site-packages/social/apps/django_app/views.py", line 28, in complete
    redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)
  File "/home/u/venv/local/lib/python2.7/site-packages/social/actions.py", line 43, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/home/u/venv/local/lib/python2.7/site-packages/social/backends/base.py", line 41, in complete
    return self.auth_complete(*args, **kwargs)
  File "/home/u/venv/local/lib/python2.7/site-packages/social/utils.py", line 229, in wrapper
    return func(*args, **kwargs)
  File "/home/u/venv/local/lib/python2.7/site-packages/social/backends/oauth.py", line 385, in auth_complete
    print(dict(response))
IOError: [Errno 5] Input/output error
```

**Comment by bgarcial** [comment]
I have yesterday recently this same error in my t2-micro ec2 instance free in amazon web services. I've fixed of this way .. http://stackoverflow.com/questions/34643170/amazon-django-each-12-hours-appears-that-errno-5-input-output-error 

Although my situation was for my code. I share the question and answer just in case.

**Comment by omab** [comment]
Since the error is in a `print` statement, I would assume that the server stdout is closed, thus producing an IO error when trying to write to it.
