### ISSUE TITLE
attribute error in django social auth package

### ISSUE THREAD

**Issue by sarfrajimpinge** [omab/python-social-auth#724]
I am trying to implement login with facebook in my django project but it gives an attribute error 'NoneType' object has no attribute 'rsplit' in django social auth package.

 In my settings.py file i have included following related to social auth : 

AUTHENTICATION_BACKENDS = (
    'social.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
MIDDLEWARE_CLASSES = (
social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
) 

TEMPLATE_CONTEXT_PROCESSORS = (
'social.apps.django_app.context_processors.backends', 'social.apps.django_app.context_processors.login_redirect',
)
SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_by_email',
    'social.pipeline.mail.mail_validation',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details'
)
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True
SOCIAL_AUTH_FACEBOOK_EXTRA_DATA = [
    ('id', 'id'),
    ('first_name', 'first_name'),
    ('last_name', 'last_name'),
    ('email', 'email'),
]

SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,email', # needed starting from protocol v2.4
}

**Comment by vyscond** [comment]
Can you post the full traceback?

**Comment by saritasa** [comment]
```
Traceback (most recent call last):
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: value too long for type character varying(30)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/braces/views/_forms.py", line 22, in dispatch
    return super(CsrfExemptMixin, self).dispatch(*args, **kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/rest_framework_social_oauth2/views.py", line 34, in post
    url, headers, body, status = self.create_token_response(request)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/oauth2_provider/views/mixins.py", line 124, in create_token_response
    return core.create_token_response(request)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/oauth2_provider/oauth2_backends.py", line 126, in create_token_response
    headers)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/rest_framework_social_oauth2/oauth2_endpoints.py", line 60, in create_token_response
    request, self.default_token_type)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/grant_types/refresh_token.py", line 58, in create_token_response
    self.validate_token_request(request)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/rest_framework_social_oauth2/oauth2_grants.py", line 91, in validate_token_request
    user = backend.do_auth(access_token=request.token)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/social/backends/facebook.py", line 119, in do_auth
    return self.strategy.authenticate(*args, **kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/social/strategies/django_strategy.py", line 96, in authenticate
    return authenticate(*args, **kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/social/backends/base.py", line 82, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/social/backends/base.py", line 85, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/social/backends/base.py", line 112, in run_pipeline
    result = func(*args, **out) or {}
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/social/pipeline/user.py", line 70, in create_user
    'user': strategy.create_user(**fields)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/social/strategies/base.py", line 53, in create_user
    return self.storage.user.create_user(*args, **kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/social/storage/django_orm.py", line 60, in create_user
    return cls.user_model().objects.create_user(*args, **kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/contrib/auth/models.py", line 187, in create_user
    **extra_fields)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/contrib/auth/models.py", line 182, in _create_user
    user.save(using=self._db)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/dmitry/Projects/bme/containers/backend/.venv/bme/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(30)

[07/Oct/2015 23:38:35] "POST /api/v1/oauth/convert-token HTTP/1.1" 500 330455
```

**Comment by Amar-Chaudhari** [comment]
@sarfrajimpinge are you able to get email address with these settings ?
It just doesnt work for me, response does not return email key
