### ISSUE TITLE
flask_me_example isn't working

### ISSUE THREAD

**Issue by llima3000** [omab/python-social-auth#730]
Hi!

I'm trying to run the flask_me_example but i'm getting the following error when I'm accessing Google Oauth2 or Facebook:

The example in django is working fine...

Any clue? 

The Traceback is here:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/social/apps/flask_app/utils.py", line 46, in wrapper
    return func(backend, _args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social/apps/flask_app/routes.py", line 23, in complete
    _args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social/actions.py", line 43, in do_complete
    user = backend.complete(user=user, _args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social/backends/base.py", line 41, in complete
    return self.auth_complete(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social/utils.py", line 229, in wrapper
    return func(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social/backends/facebook.py", line 87, in auth_complete
    return self.do_auth(access_token, response, _args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social/backends/facebook.py", line 119, in do_auth
    return self.strategy.authenticate(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social/strategies/base.py", line 148, in authenticate
    return backend.authenticate(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social/backends/base.py", line 82, in authenticate
    return self.pipeline(pipeline, _args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social/backends/base.py", line 85, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, _args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social/backends/base.py", line 112, in run_pipeline
    result = func(_args, *_out) or {}
  File "/usr/local/lib/python2.7/site-packages/social/pipeline/social_auth.py", line 20, in social_user
    social = backend.strategy.storage.user.get_social_auth(provider, uid)
  File "/usr/local/lib/python2.7/site-packages/social/storage/sqlalchemy_orm.py", line 134, in get_social_auth
    return cls._query().filter_by(provider=provider,
  File "/usr/local/lib/python2.7/site-packages/social/storage/sqlalchemy_orm.py", line 36, in _query
    return cls._session().query(cls)
  File "/usr/local/lib/python2.7/site-packages/social/apps/flask_app/default/models.py", line 27, in _session
    return cls.app_session
AttributeError: type object 'UserSocialAuth' has no attribute 'app_session'

**Comment by dotpot** [comment]
same thing here! getting exactly the same error.

**Comment by omab** [comment]
The example apps were updated recently, they now reside in [social-examples](https://github.com/python-social-auth/social-examples).
