### ISSUE TITLE
Migration error on update 0.2.6 -> 0.2.7

### ISSUE THREAD

**Issue by dbrgn** [omab/python-social-auth#761]
After upgrading from PSA 0.2.6 to 0.2.7, I get the following error message when running the migrations:

```
  Applying default.0003_alter_email_max_length...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 160, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/db/migrations/executor.py", line 63, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/db/migrations/executor.py", line 97, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/db/migrations/migration.py", line 107, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 139, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/db/backends/schema.py", line 473, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type, old_db_params, new_db_params, strict)
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/db/backends/schema.py", line 626, in _alter_field
    params,
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/db/backends/schema.py", line 99, in execute
    cursor.execute(sql, params)
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/danilo/.virtualenvs/radar/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "social_auth_code" does not exist
```

Any ideas?

**Comment by dbrgn** [comment]
After re-creating the database locally, everything works fine. Maybe my local dev system was broken somehow. I'll try to see if the stage system can be upgraded, until then I'll close this issue.

**Comment by dbrgn** [comment]
Duplicate of #682.
