### ISSUE TITLE
Steam SSL error

### ISSUE THREAD

**Issue by recfunc** [omab/python-social-auth#918]
**Sometimes** I get this error. How can I fix it?

ERROR:django.request:Internal Server Error: /login/steam/
Traceback (most recent call last):
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/openid/fetchers.py", line 192, in fetch
    return self.fetcher.fetch(_args, *_kwargs)
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/openid/fetchers.py", line 404, in fetch
    c.perform()
pycurl.error: (51, "SSL: no alternative certificate subject name matches target host name 'steamcommunity.com'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/openid/consumer/consumer.py", line 343, in begin
    service = disco.getNextService(self._discover)
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/openid/yadis/manager.py", line 105, in getNextService
    yadis_url, services = discover(self.url)
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/openid/consumer/discover.py", line 471, in discover
    return discoverURI(identifier)
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/openid/consumer/discover.py", line 463, in discoverURI
    claimed_id, openid_services = discoverYadis(uri)
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/openid/consumer/discover.py", line 390, in discoverYadis
    response = yadisDiscover(uri)
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/openid/yadis/discover.py", line 72, in discover
    resp = fetchers.fetch(uri, headers={'Accept': YADIS_ACCEPT_HEADER})
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/openid/fetchers.py", line 48, in fetch
    return fetcher.fetch(url, body, headers)
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/openid/fetchers.py", line 201, in fetch
    raise HTTPFetchingError(why=exc_inst)
openid.fetchers.HTTPFetchingError: (51, "SSL: no alternative certificate subject name matches target host name 'steamcommunity.com'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/social/backends/open_id.py", line 245, in openid_request
    params))
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/openid/consumer/consumer.py", line 346, in begin
    'Error fetching XRDS document: %s' % (why.why,), None)
openid.yadis.discover.DiscoveryFailure: Error fetching XRDS document: (51, "SSL: no alternative certificate subject name matches target host name 'steamcommunity.com'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, _args, *_kwargs)
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/social/apps/django_app/utils.py", line 51, in wrapper
    return func(request, backend, _args, *_kwargs)
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/social/apps/django_app/views.py", line 19, in auth
    return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/social/actions.py", line 28, in do_auth
    return backend.start()
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/social/backends/base.py", line 35, in start
    if self.uses_redirect():
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/social/backends/open_id.py", line 239, in uses_redirect
    return self.openid_request().shouldSendRedirect()
  File "/home/steam-tools/steam-tools/lib/python3.4/site-packages/social/backends/open_id.py", line 248, in openid_request
    err
social.exceptions.AuthException: OpenID discovery error: Error fetching XRDS document: (51, "SSL: no alternative certificate subject name matches target host name 'steamcommunity.com'")

**Comment by omab** [comment]
This seems to be a problem with Steam since the common name for their certificate for `steamcommunity.com` points to `store.steampowered.com`.
